/*
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/// End-to-end tests that read real Paimon ORC files generated by the Java
/// Paimon API. These tests validate the Velox Paimon connector against actual
/// Paimon table data at /data/test/paimon/db1.
///
/// Test data layout:
///   append_table: 1 snapshot, 1 ORC file, 5 rows
///     Schema: id(INT), name(STRING), amount(BIGINT), price(FLOAT),
///             score(DOUBLE), active(BOOLEAN), event_date(DATE),
///             total(DECIMAL(10,2)), event_time(TIMESTAMP(3))
///
///   pk_table: 2 snapshots (deduplicate merge engine), 2 ORC files, 7 raw rows
///     Schema (user columns): user_id(BIGINT), name(STRING), score(DOUBLE),
///                            level(INT), updated_at(TIMESTAMP(3))
///     ORC KV schema: _KEY_user_id, _SEQUENCE_NUMBER, _VALUE_KIND,
///                    user_id, name, score, level, updated_at
///     After merge: 5 unique rows (user_id 1,3 updated; user_id 5 new)

#include "velox/connectors/hive/paimon/PaimonConnector.h"

#include <folly/init/Init.h>
#include <gtest/gtest.h>
#include <filesystem>

#include "velox/common/base/tests/GTestUtils.h"
#include "velox/connectors/ConnectorRegistry.h"
#include "velox/connectors/hive/HiveConfig.h"
#include "velox/connectors/hive/paimon/PaimonConnectorSplit.h"
#include "velox/dwio/orc/reader/OrcReader.h"
#include "velox/exec/tests/utils/AssertQueryBuilder.h"
#include "velox/exec/tests/utils/HiveConnectorTestBase.h"
#include "velox/exec/tests/utils/PlanBuilder.h"

namespace facebook::velox::connector::hive::paimon {
namespace {

static const std::string kPaimonConnectorId = "test-paimon-e2e";
static const std::string kWarehouse = "/data/test/paimon/db1/test_db.db";

class PaimonE2ETest : public exec::test::HiveConnectorTestBase {
 protected:
  void SetUp() override {
    HiveConnectorTestBase::SetUp();
    orc::registerOrcReaderFactory();
    auto config = std::make_shared<config::ConfigBase>(
        std::unordered_map<std::string, std::string>{});
    auto connector =
        PaimonConnectorFactory().newConnector(kPaimonConnectorId, config);
    ConnectorRegistry::global().insert(connector->connectorId(), connector);
  }

  void TearDown() override {
    ConnectorRegistry::global().erase(kPaimonConnectorId);
    HiveConnectorTestBase::TearDown();
  }

  static std::shared_ptr<HiveTableHandle> makePaimonTableHandle(
      const RowTypePtr& dataColumns = nullptr,
      common::SubfieldFilters subfieldFilters = {},
      const core::TypedExprPtr& remainingFilter = nullptr) {
    return std::make_shared<HiveTableHandle>(
        kPaimonConnectorId,
        "paimon_table",
        std::move(subfieldFilters),
        remainingFilter,
        dataColumns);
  }

  static connector::ColumnHandleMap makePaimonColumnHandles(
      const RowTypePtr& rowType) {
    connector::ColumnHandleMap assignments;
    assignments.reserve(rowType->size());
    for (uint32_t i = 0; i < rowType->size(); ++i) {
      const auto& name = rowType->nameOf(i);
      assignments[name] = std::make_shared<HiveColumnHandle>(
          name,
          HiveColumnHandle::ColumnType::kRegular,
          rowType->childAt(i),
          rowType->childAt(i));
    }
    return assignments;
  }

  core::PlanNodePtr makePaimonScanPlan(
      const RowTypePtr& outputType,
      const RowTypePtr& dataColumns = nullptr) {
    auto tableHandle =
        makePaimonTableHandle(dataColumns ? dataColumns : outputType);
    auto assignments =
        makePaimonColumnHandles(dataColumns ? dataColumns : outputType);
    return exec::test::PlanBuilder()
        .startTableScan()
        .connectorId(kPaimonConnectorId)
        .outputType(outputType)
        .tableHandle(tableHandle)
        .assignments(assignments)
        .endTableScan()
        .planNode();
  }

  /// Lists ORC files in a Paimon bucket directory.
  static std::vector<std::string> listOrcFiles(const std::string& dir) {
    std::vector<std::string> files;
    for (const auto& entry : std::filesystem::directory_iterator(dir)) {
      if (entry.path().extension() == ".orc") {
        files.push_back(entry.path().string());
      }
    }
    std::sort(files.begin(), files.end());
    return files;
  }

  /// Executes a plan with the given splits and returns all result rows.
  RowVectorPtr execute(
      const core::PlanNodePtr& plan,
      const std::vector<std::shared_ptr<connector::ConnectorSplit>>& splits) {
    auto builder = exec::test::AssertQueryBuilder(plan);
    for (const auto& split : splits) {
      builder.split(split);
    }
    return builder.copyResults(pool());
  }
};

// Read the append-only table's ORC file and verify row count.
TEST_F(PaimonE2ETest, appendOnlyReadRowCount) {
  auto files =
      listOrcFiles(kWarehouse + "/append_table/bucket-0");
  ASSERT_EQ(files.size(), 1) << "Expected 1 ORC file for append_table";

  // Append-only table schema: id, name, amount, price, score, active,
  // event_date, total, event_time
  auto outputType = ROW(
      {"id", "name", "amount", "price", "score", "active", "event_date",
       "total", "event_time"},
      {INTEGER(),
       VARCHAR(),
       BIGINT(),
       REAL(),
       DOUBLE(),
       BOOLEAN(),
       DATE(),
       DECIMAL(10, 2),
       TIMESTAMP()});

  PaimonConnectorSplitBuilder builder(
      kPaimonConnectorId,
      /*snapshotId=*/1,
      PaimonTableType::kAppendOnly,
      dwio::common::FileFormat::ORC);
  builder.addFile(files[0], /*fileSize=*/0);
  builder.rawConvertible(true);
  auto split = builder.build();

  auto plan = makePaimonScanPlan(outputType);
  auto result = execute(plan, {split});

  ASSERT_EQ(result->size(), 5) << "append_table should have 5 rows";
}

// Read the append-only table and verify specific column values.
TEST_F(PaimonE2ETest, appendOnlyVerifyData) {
  auto files =
      listOrcFiles(kWarehouse + "/append_table/bucket-0");
  ASSERT_EQ(files.size(), 1);

  // Read just id, name, amount, active columns for verification.
  auto outputType =
      ROW({"id", "name", "amount", "active"},
          {INTEGER(), VARCHAR(), BIGINT(), BOOLEAN()});

  // dataColumns must describe the full schema for the connector to locate
  // columns correctly in the ORC file.
  auto dataColumns = ROW(
      {"id", "name", "amount", "price", "score", "active", "event_date",
       "total", "event_time"},
      {INTEGER(),
       VARCHAR(),
       BIGINT(),
       REAL(),
       DOUBLE(),
       BOOLEAN(),
       DATE(),
       DECIMAL(10, 2),
       TIMESTAMP()});

  PaimonConnectorSplitBuilder builder(
      kPaimonConnectorId,
      /*snapshotId=*/1,
      PaimonTableType::kAppendOnly,
      dwio::common::FileFormat::ORC);
  builder.addFile(files[0], /*fileSize=*/0);
  builder.rawConvertible(true);
  auto split = builder.build();

  auto plan = makePaimonScanPlan(outputType, dataColumns);
  auto result = execute(plan, {split});

  ASSERT_EQ(result->size(), 5);

  // Extract columns.
  auto ids = result->childAt(0)->asFlatVector<int32_t>();
  auto names = result->childAt(1)->asFlatVector<StringView>();
  auto amounts = result->childAt(2)->asFlatVector<int64_t>();
  auto actives = result->childAt(3)->asFlatVector<bool>();

  // Build a map of id -> row index for order-independent verification.
  std::unordered_map<int32_t, vector_size_t> idToRow;
  for (vector_size_t i = 0; i < result->size(); ++i) {
    idToRow[ids->valueAt(i)] = i;
  }

  // Verify Alice (id=1).
  ASSERT_TRUE(idToRow.count(1));
  auto row = idToRow[1];
  EXPECT_EQ(names->valueAt(row).getString(), "Alice");
  EXPECT_EQ(amounts->valueAt(row), 100);
  EXPECT_TRUE(actives->valueAt(row));

  // Verify Bob (id=2).
  ASSERT_TRUE(idToRow.count(2));
  row = idToRow[2];
  EXPECT_EQ(names->valueAt(row).getString(), "Bob");
  EXPECT_EQ(amounts->valueAt(row), 200);
  EXPECT_FALSE(actives->valueAt(row));

  // Verify Charlie (id=3).
  ASSERT_TRUE(idToRow.count(3));
  row = idToRow[3];
  EXPECT_EQ(names->valueAt(row).getString(), "Charlie");
  EXPECT_EQ(amounts->valueAt(row), 300);

  // Verify Diana (id=4).
  ASSERT_TRUE(idToRow.count(4));
  row = idToRow[4];
  EXPECT_EQ(names->valueAt(row).getString(), "Diana");
  EXPECT_EQ(amounts->valueAt(row), 400);

  // Verify Eve (id=5).
  ASSERT_TRUE(idToRow.count(5));
  row = idToRow[5];
  EXPECT_EQ(names->valueAt(row).getString(), "Eve");
  EXPECT_EQ(amounts->valueAt(row), 500);
}

// Read the append-only table with column projection (subset of columns).
TEST_F(PaimonE2ETest, appendOnlyColumnProjection) {
  auto files =
      listOrcFiles(kWarehouse + "/append_table/bucket-0");
  ASSERT_EQ(files.size(), 1);

  // Project only score and name columns.
  auto outputType = ROW({"score", "name"}, {DOUBLE(), VARCHAR()});

  // dataColumns must describe the full schema for the connector to locate
  // columns correctly in the ORC file.
  auto dataColumns = ROW(
      {"id", "name", "amount", "price", "score", "active", "event_date",
       "total", "event_time"},
      {INTEGER(),
       VARCHAR(),
       BIGINT(),
       REAL(),
       DOUBLE(),
       BOOLEAN(),
       DATE(),
       DECIMAL(10, 2),
       TIMESTAMP()});

  PaimonConnectorSplitBuilder builder(
      kPaimonConnectorId,
      /*snapshotId=*/1,
      PaimonTableType::kAppendOnly,
      dwio::common::FileFormat::ORC);
  builder.addFile(files[0], /*fileSize=*/0);
  builder.rawConvertible(true);
  auto split = builder.build();

  auto plan = makePaimonScanPlan(outputType, dataColumns);
  auto result = execute(plan, {split});

  ASSERT_EQ(result->size(), 5);
  ASSERT_EQ(result->type()->size(), 2);
  EXPECT_EQ(result->type()->as<TypeKind::ROW>().nameOf(0), "score");
  EXPECT_EQ(result->type()->as<TypeKind::ROW>().nameOf(1), "name");
}

// Read the append-only table and verify numeric precision (price as REAL,
// score as DOUBLE).
TEST_F(PaimonE2ETest, appendOnlyNumericPrecision) {
  auto files =
      listOrcFiles(kWarehouse + "/append_table/bucket-0");
  ASSERT_EQ(files.size(), 1);

  auto outputType =
      ROW({"id", "price", "score"}, {INTEGER(), REAL(), DOUBLE()});

  auto dataColumns = ROW(
      {"id", "name", "amount", "price", "score", "active", "event_date",
       "total", "event_time"},
      {INTEGER(),
       VARCHAR(),
       BIGINT(),
       REAL(),
       DOUBLE(),
       BOOLEAN(),
       DATE(),
       DECIMAL(10, 2),
       TIMESTAMP()});

  PaimonConnectorSplitBuilder builder(
      kPaimonConnectorId,
      /*snapshotId=*/1,
      PaimonTableType::kAppendOnly,
      dwio::common::FileFormat::ORC);
  builder.addFile(files[0], /*fileSize=*/0);
  builder.rawConvertible(true);
  auto split = builder.build();

  auto plan = makePaimonScanPlan(outputType, dataColumns);
  auto result = execute(plan, {split});

  ASSERT_EQ(result->size(), 5);

  auto ids = result->childAt(0)->asFlatVector<int32_t>();
  auto prices = result->childAt(1)->asFlatVector<float>();
  auto scores = result->childAt(2)->asFlatVector<double>();

  std::unordered_map<int32_t, vector_size_t> idToRow;
  for (vector_size_t i = 0; i < result->size(); ++i) {
    idToRow[ids->valueAt(i)] = i;
  }

  // Alice: price=9.99, score=95.5
  ASSERT_TRUE(idToRow.count(1));
  EXPECT_NEAR(prices->valueAt(idToRow[1]), 9.99f, 0.01f);
  EXPECT_NEAR(scores->valueAt(idToRow[1]), 95.5, 0.001);

  // Bob: price=19.99, score=88.0
  ASSERT_TRUE(idToRow.count(2));
  EXPECT_NEAR(prices->valueAt(idToRow[2]), 19.99f, 0.01f);
  EXPECT_NEAR(scores->valueAt(idToRow[2]), 88.0, 0.001);
}

// PK table: read with rawConvertible=false (merge-on-read).
// Two ORC files with overlapping keys should produce 5 deduplicated rows.
TEST_F(PaimonE2ETest, pkTableMergeOnRead) {
  auto files = listOrcFiles(kWarehouse + "/pk_table/bucket-0");
  ASSERT_EQ(files.size(), 2) << "Expected 2 ORC files for pk_table";

  // User-facing output columns (no system columns).
  auto outputType = ROW(
      {"user_id", "name", "score", "level"},
      {BIGINT(), VARCHAR(), DOUBLE(), INTEGER()});

  PaimonConnectorSplitBuilder builder(
      kPaimonConnectorId,
      /*snapshotId=*/2,
      PaimonTableType::kPrimaryKey,
      dwio::common::FileFormat::ORC);

  // Add files with distinct levels so merge-on-read sees them correctly.
  // File 0 (snapshot-1 data, older) at level 1.
  // File 1 (snapshot-2 data, newer) at level 0.
  // Sorted by name: data-02... is file1(snapshot-2), data-04... is
  // file0(snapshot-1). We use sequence numbers to determine order.
  for (size_t i = 0; i < files.size(); ++i) {
    // Level assignment: first file (alphabetically) at level 0,
    // second at level 1. Sequence numbers determine winner.
    builder.addFile(files[i], /*fileSize=*/0, /*level=*/static_cast<int32_t>(i));
  }
  builder.rawConvertible(false);
  builder.primaryKeys({"user_id"});
  builder.mergeEngine("deduplicate");
  builder.tableBucketNumber(0);
  auto split = builder.build();

  auto plan = makePaimonScanPlan(outputType);
  auto result = execute(plan, {split});

  // After merge, should have 5 unique user_ids.
  ASSERT_EQ(result->size(), 5)
      << "pk_table should have 5 rows after merge-on-read";

  auto userIds = result->childAt(0)->asFlatVector<int64_t>();
  auto names = result->childAt(1)->asFlatVector<StringView>();
  auto scores = result->childAt(2)->asFlatVector<double>();
  auto levels = result->childAt(3)->asFlatVector<int32_t>();

  std::unordered_map<int64_t, vector_size_t> idToRow;
  for (vector_size_t i = 0; i < result->size(); ++i) {
    idToRow[userIds->valueAt(i)] = i;
  }

  // Verify all 5 user_ids are present.
  EXPECT_TRUE(idToRow.count(1));
  EXPECT_TRUE(idToRow.count(2));
  EXPECT_TRUE(idToRow.count(3));
  EXPECT_TRUE(idToRow.count(4));
  EXPECT_TRUE(idToRow.count(5));

  // user_id=1: updated in commit 2 -> score=97.0, level=11
  EXPECT_EQ(names->valueAt(idToRow[1]).getString(), "Alice");
  EXPECT_NEAR(scores->valueAt(idToRow[1]), 97.0, 0.001);
  EXPECT_EQ(levels->valueAt(idToRow[1]), 11);

  // user_id=2: not updated -> score=88.0, level=8
  EXPECT_EQ(names->valueAt(idToRow[2]).getString(), "Bob");
  EXPECT_NEAR(scores->valueAt(idToRow[2]), 88.0, 0.001);
  EXPECT_EQ(levels->valueAt(idToRow[2]), 8);

  // user_id=3: updated in commit 2 -> score=78.5, level=6
  EXPECT_EQ(names->valueAt(idToRow[3]).getString(), "Charlie");
  EXPECT_NEAR(scores->valueAt(idToRow[3]), 78.5, 0.001);
  EXPECT_EQ(levels->valueAt(idToRow[3]), 6);

  // user_id=4: not updated -> score=91.7, level=9
  EXPECT_EQ(names->valueAt(idToRow[4]).getString(), "Diana");
  EXPECT_NEAR(scores->valueAt(idToRow[4]), 91.7, 0.001);
  EXPECT_EQ(levels->valueAt(idToRow[4]), 9);

  // user_id=5: new in commit 2 -> score=85.0, level=7
  EXPECT_EQ(names->valueAt(idToRow[5]).getString(), "Eve");
  EXPECT_NEAR(scores->valueAt(idToRow[5]), 85.0, 0.001);
  EXPECT_EQ(levels->valueAt(idToRow[5]), 7);
}

// PK table: read with column projection on merge path.
TEST_F(PaimonE2ETest, pkTableMergeColumnProjection) {
  auto files = listOrcFiles(kWarehouse + "/pk_table/bucket-0");
  ASSERT_EQ(files.size(), 2);

  // Only project user_id and score.
  auto outputType = ROW({"user_id", "score"}, {BIGINT(), DOUBLE()});

  PaimonConnectorSplitBuilder builder(
      kPaimonConnectorId,
      /*snapshotId=*/2,
      PaimonTableType::kPrimaryKey,
      dwio::common::FileFormat::ORC);

  for (size_t i = 0; i < files.size(); ++i) {
    builder.addFile(files[i], /*fileSize=*/0, /*level=*/static_cast<int32_t>(i));
  }
  builder.rawConvertible(false);
  builder.primaryKeys({"user_id"});
  builder.mergeEngine("deduplicate");
  builder.tableBucketNumber(0);
  auto split = builder.build();

  auto plan = makePaimonScanPlan(outputType);
  auto result = execute(plan, {split});

  ASSERT_EQ(result->size(), 5);
  ASSERT_EQ(result->type()->size(), 2);

  auto userIds = result->childAt(0)->asFlatVector<int64_t>();
  auto scores = result->childAt(1)->asFlatVector<double>();

  std::unordered_map<int64_t, double> idToScore;
  for (vector_size_t i = 0; i < result->size(); ++i) {
    idToScore[userIds->valueAt(i)] = scores->valueAt(i);
  }

  EXPECT_NEAR(idToScore[1], 97.0, 0.001);
  EXPECT_NEAR(idToScore[2], 88.0, 0.001);
  EXPECT_NEAR(idToScore[3], 78.5, 0.001);
  EXPECT_NEAR(idToScore[4], 91.7, 0.001);
  EXPECT_NEAR(idToScore[5], 85.0, 0.001);
}

} // namespace
} // namespace facebook::velox::connector::hive::paimon

int main(int argc, char** argv) {
  testing::InitGoogleTest(&argc, argv);
  folly::Init init{&argc, &argv, false};
  return RUN_ALL_TESTS();
}
